"""
Django settings for voice_bot project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from dotenv import load_dotenv
import os
from datetime import timedelta
from corsheaders.defaults import default_headers

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))

AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT")
AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION")
ELEVENLABS_API_KEY = os.getenv("ELEVENLABS_API_KEY")

# Azure Blob Storage settings are configured dynamically below.

WA_SENDER_API_KEY = os.getenv("WA_SENDER_API_KEY")
WA_SENDER_WEBHOOK_SECRET = os.getenv("WA_SENDER_WEBHOOK_SECRET")
WA_SENDER_BASE_URL = os.getenv("WA_SENDER_BASE_URL")



# AZURE_TRANSLATOR_KEY = os.getenv("AZURE_TRANSLATOR_KEY")
# AZURE_TRANSLATOR_REGION = os.getenv("AZURE_TRANSLATOR_REGION")
# AZURE_TRANSLATE_ENDPOINT = os.getenv("AZURE_TRANSLATE_ENDPOINT")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*7s*aaz)wrq!lexszd)#u*k!f^uv^imr70+j)7rk-xhq8*l(5k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
ALLOWED_HOSTS = ["*","multivoicebot-d3eyanb4h2g4crhh.centralindia-01.azurewebsites.net", "insurancebot-b3aha4cmfnbghza7.centralindia-01.azurewebsites.net"]


CSRF_TRUSTED_ORIGINS = [
    "https://multivoicebot-d3eyanb4h2g4crhh.centralindia-01.azurewebsites.net",
    "https://renav-ch.on-forge.com",
    "https://insurancebot-b3aha4cmfnbghza7.centralindia-01.azurewebsites.net",
    "https://voicebotsaas-dterfndqfbfqfkhd.centralindia-01.azurewebsites.net"
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CORS_ALLOW_METHODS = ['GET', 'POST', 'OPTIONS']

CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-api-key",
    "ngrok-skip-browser-warning",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://multivoicebot-d3eyanb4h2g4crhh.centralindia-01.azurewebsites.net",
    "https://voicebotsaas-dterfndqfbfqfkhd.centralindia-01.azurewebsites.net",
    "https://renav-ch.on-forge.com",
]
# Application definition

CORS_ALLOW_CREDENTIALS = True


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "channels", 

    "agents",
    "knowledge",
    "conversations",
    "assistant",
    "accounts",
    "customers",
    "rest_framework",
    "corsheaders",
    "bot",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'voice_bot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'voice_bot.wsgi.application'

#for wesocket
ASGI_APPLICATION = "voice_bot.asgi.application"


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# =========================
# DATABASE CONFIGURATION
# Local SQLite + Azure PostgreSQL
# =========================

if DEBUG:

    # 🔹 LOCAL DATABASE
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 20,
            }
        }
    }

    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'


else:

    # 🔹 AZURE POSTGRESQL DATABASE

    CONNECTION_STRING = os.environ.get('AZURE_POSTGRESQL_CONNECTIONSTRING')

    if CONNECTION_STRING:
        conn_str_params = dict(
            pair.split('=', 1) for pair in CONNECTION_STRING.split(' ')
        )

        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': conn_str_params.get('dbname'),
                'HOST': conn_str_params.get('host'),
                'USER': conn_str_params.get('user'),
                'PASSWORD': conn_str_params.get('password'),
                'PORT': conn_str_params.get('port', '5432'),
                'OPTIONS': {
                    'sslmode': 'require',
                }
            }
        }
    else:
        # Fallback to local SQLite if no connection string is provided
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), 
       # os.path.join(BASE_DIR, 'bot', 'static'),
]

# ✅ Azure Storage & Media Configuration
USE_AZURE_MEDIA = os.environ.get("USE_AZURE_MEDIA", "0") in ("1", "true", "True") or os.environ.get("USE_AZURE_STORAGE", "False") == "True"

if USE_AZURE_MEDIA:
    AZURE_ACCOUNT_NAME = os.environ.get("AZURE_STORAGE_ACCOUNT_NAME") or os.environ.get("AZURE_ACCOUNT_NAME")
    AZURE_ACCOUNT_KEY  = os.environ.get("AZURE_STORAGE_ACCOUNT_KEY") or os.environ.get("AZURE_ACCOUNT_KEY")
    AZURE_CONTAINER    = os.environ.get("AZURE_STORAGE_CONTAINER") or os.environ.get("AZURE_MEDIA_CONTAINER", "media")
    AZURE_MEDIA_CONTAINER = AZURE_CONTAINER
    AZURE_ACCOUNT_URL  = f"https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net"
    AZURE_CUSTOM_DOMAIN = os.environ.get(
        "AZURE_STORAGE_CUSTOM_DOMAIN"
    ) or os.environ.get(
        "AZURE_CUSTOM_DOMAIN",
        f"{AZURE_ACCOUNT_NAME}.blob.core.windows.net",
    )
    # AZURE_URL_EXPIRATION_SECS = int(os.environ.get("AZURE_URL_EXPIRATION_SECS", 3600))
    AZURE_URL_EXPIRATION_SECS = None
    AZURE_OVERWRITE_FILES = False

    # ✅ New-style Django 4.2/5.x storage config
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }

    WHITENOISE_USE_FINDERS = True
    MEDIA_URL = f"https://{AZURE_CUSTOM_DOMAIN}/{AZURE_CONTAINER}/"
else:
    MEDIA_URL  = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    
    AZURE_ACCOUNT_NAME = None
    AZURE_ACCOUNT_KEY = None
    AZURE_CONTAINER = "media"
    AZURE_MEDIA_CONTAINER = "media"
    AZURE_CUSTOM_DOMAIN = None

    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=3),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}



# =========================
# DJANGO ERROR LOG FILE (PRODUCTION)
# Same as recruit_management project
# =========================

if not DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,

        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {message}',
                'style': '{',
            },
        },

        'handlers': {
            'file': {
                'level': 'ERROR',
                'class': 'logging.FileHandler',
                'filename': '/home/site/wwwroot/django_errors.log',
                'formatter': 'verbose',
            },
        },

        'loggers': {
            'django': {
                'handlers': ['file'],
                'level': 'ERROR',
                'propagate': False,
            },
        },
    }

# =========================
# EMAIL CONFIGURATION (Gmail SMTP)
# =========================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'testing251299@gmail.com'
EMAIL_HOST_PASSWORD = 'hqnc uhzo lwch iwss'
DEFAULT_FROM_EMAIL = 'AI SalesBot <testing251299@gmail.com>'
