# raahi_iiiem_bot/config.py

AGENT_NAME = "Raahi"
COMPANY_NAME = "Triple i E M"
FULL_COMPANY_NAME = "iiiEM Export Import Training Institute"
DEFAULT_VOICE = "en-IN-NeerjaNeural"
DEFAULT_LANGUAGE = "hi"  # Default initial TTS voice setting (Hinglish/Hindi/English dynamic)

MAX_MESSAGE_LENGTH = 1000
MAX_TURNS = 12

# Stage definitions
STAGE_GREET = "STAGE_1_GREET"
STAGE_NEED = "STAGE_2_NEED"
STAGE_RECOMMEND = "STAGE_3_RECOMMEND"
STAGE_INFO_PREF = "STAGE_4_INFO_PREF"
STAGE_WHATSAPP_CONFIRM = "STAGE_5_WHATSAPP_CONFIRM"
STAGE_SUPPORT_PREF = "STAGE_6_SUPPORT_PREF"
STAGE_PATH_ONLINE = "STAGE_7A_ONLINE"
STAGE_PATH_CENTRE = "STAGE_7B_CENTRE"
STAGE_REGISTRATION_PUSH = "STAGE_8_REGISTRATION"
STAGE_CLOSING = "STAGE_9_CLOSING"
