# Generated by Django 6.0.2 on 2026-02-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceagent',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
