# Generated by Django 4.2.28 on 2026-03-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_voiceagent_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceagent',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
