# Generated by Django 4.2.28 on 2026-06-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_voiceagent_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceagent',
            name='minutes_quota',
            field=models.IntegerField(default=5000, help_text='Total allocated call minutes for this bot'),
        ),
    ]
