# Generated by Django 4.2.28 on 2026-06-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_voiceagent_minutes_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceagent',
            name='inbound_phone_number',
            field=models.CharField(blank=True, help_text='Twilio/Telnyx DID number (normalized) assigned to this bot', max_length=20, null=True, unique=True),
        ),
    ]
