# Generated by Django 4.2.28 on 2026-07-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_voiceagent_inbound_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceagent',
            name='max_concurrent_calls',
            field=models.IntegerField(default=2, help_text='Maximum concurrent calls for campaigns using this bot.'),
        ),
    ]
