# Generated by Django 4.2.28 on 2026-08-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_voiceagent_max_concurrent_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceagent',
            name='extra_used_minutes',
            field=models.FloatField(default=0.0, help_text='Manual adjustment added to auto-calculated call duration'),
        ),
    ]
