# Generated by Django 4.2.28 on 2026-05-06 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_voiceagent_summary'),
        ('conversations', '0003_conversation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_level', models.CharField(choices=[('hot', 'Hot — Interested to buy'), ('warm', 'Warm — Mid-level interest'), ('cold', 'Cold — Low interest'), ('not_interested', 'Not Interested')], max_length=20)),
                ('user_name', models.CharField(blank=True, default='', max_length=255)),
                ('user_email', models.CharField(blank=True, default='', max_length=255)),
                ('user_phone', models.CharField(blank=True, default='', max_length=50)),
                ('interest_topic', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('raw_analysis', models.JSONField(blank=True, default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.voiceagent')),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_analysis', to='conversations.conversation')),
            ],
            options={
                'verbose_name': 'Lead Analysis',
                'verbose_name_plural': 'Lead Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
