# Generated by Django 4.2.28 on 2026-05-06 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_leadanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telecom_call_id', models.IntegerField(help_text='Telecom internal call ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('calldate', models.DateTimeField()),
                ('did', models.CharField(help_text='DID number (bot phone number)', max_length=20)),
                ('duration', models.IntegerField(default=0, help_text='Call duration in seconds')),
                ('disposition', models.CharField(choices=[('ANSWERED', 'Answered'), ('NO ANSWER', 'No Answer'), ('BUSY', 'Busy'), ('FAILED', 'Failed')], default='ANSWERED', max_length=20)),
                ('call_type', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], default='OUTBOUND', max_length=10)),
                ('answer_time', models.DateTimeField(blank=True, null=True)),
                ('uniqueid', models.CharField(help_text='Telecom unique ID', max_length=50, unique=True)),
                ('recording_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('matched', models.BooleanField(default=False, help_text='Whether matched to a Conversation')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(blank=True, help_text='Matched conversation (via recording_file_name → session_id)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdr', to='conversations.conversation')),
            ],
            options={
                'verbose_name': 'Call Detail Record',
                'verbose_name_plural': 'Call Detail Records',
                'ordering': ['-received_at'],
            },
        ),
    ]
