# Generated by Django 5.2.13 on 2026-05-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_calldetailrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='stream_sid',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
