# Generated by Django 4.2.28 on 2026-06-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_conversation_stream_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='campaign_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
