# Generated by Django 4.2.28 on 2026-06-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_conversation_campaign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='call_type',
            field=models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], db_index=True, default='OUTBOUND', max_length=10),
        ),
    ]
