# Generated by Django 4.2.28 on 2026-06-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0008_conversation_call_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadanalysis',
            name='appointment_date',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
