# Generated by Django 4.2.28 on 2026-07-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0009_leadanalysis_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadanalysis',
            name='lead_level',
            field=models.CharField(choices=[('hot', 'Hot — Interested to buy'), ('warm', 'Warm — Mid-level interest'), ('cold', 'Cold — Low interest'), ('not_interested', 'Not Interested'), ('missed', 'Missed Call')], max_length=20),
        ),
    ]
