# Generated by Django 4.2.28 on 2026-09-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0011_alter_leadanalysis_lead_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SarvamCallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('interaction_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('candidate_name', models.CharField(default='Candidate', max_length=255)),
                ('language', models.CharField(default='hi-IN', max_length=50)),
                ('applied_position', models.CharField(default='Admission Counselor', max_length=255)),
                ('status', models.CharField(default='DIALING', max_length=100)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('audio_url', models.TextField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sarvam Call Record',
                'verbose_name_plural': 'Sarvam Call Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
