# Generated by Django 4.2.28 on 2026-09-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0012_sarvamcallrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarvamcallrecord',
            name='call_type',
            field=models.CharField(default='Live Call', max_length=50),
        ),
        migrations.AddField(
            model_name='sarvamcallrecord',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sarvamcallrecord',
            name='interaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
