# Generated by Django 4.2.28 on 2026-09-12 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0013_add_calltype_starttime_to_sarvamcallrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SarvamAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable agent name, e.g. 'Raahi - iiiEM'", max_length=100)),
                ('slug', models.SlugField(help_text="URL-safe identifier, e.g. 'raahi-iiiem', 'new-agent'", unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='What this agent does')),
                ('org_id', models.CharField(help_text='SARVAM_ORG_ID', max_length=150)),
                ('workspace_id', models.CharField(help_text='SARVAM_WORKSPACE_ID', max_length=150)),
                ('app_id', models.CharField(help_text='SARVAM_AGENT_ID (app_id on Sarvam platform)', max_length=150)),
                ('api_key', models.CharField(help_text='SARVAM_AGENT_API_KEY (sk_samvaad_...)', max_length=300)),
                ('connection_id', models.CharField(help_text='SARVAM_CONNECTION_ID', max_length=150)),
                ('agent_phone', models.CharField(help_text='Phone number Sarvam dials from, e.g. +917971414121', max_length=25)),
                ('webhook_domain', models.CharField(blank=True, default='', help_text='Public domain for CDR webhooks, e.g. https://yourngrok.ngrok-free.dev', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sarvam Agent',
                'verbose_name_plural': 'Sarvam Agents',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sarvamcallrecord',
            name='sarvam_agent',
            field=models.ForeignKey(blank=True, help_text='Which Sarvam voice agent made this call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='conversations.sarvamagent'),
        ),
    ]
