# Generated by Django 4.2.28 on 2026-09-14 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0014_sarvam_agent_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SarvamCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Excel Campaign', max_length=255)),
                ('excel_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('total_leads', models.IntegerField(default=0)),
                ('current_stage', models.IntegerField(choices=[(1, 'Stage 1: Main Campaign'), (2, 'Stage 2: Retry #1'), (3, 'Stage 3: Final Retry #2'), (4, 'All Stages Completed')], default=1)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING_MAIN', 'Running Main Campaign'), ('RUNNING_RETRY_1', 'Running Retry #1'), ('RUNNING_RETRY_2', 'Running Retry #2 (Final)'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=50)),
                ('stage_1_dispatched', models.IntegerField(default=0)),
                ('stage_1_answered', models.IntegerField(default=0)),
                ('stage_1_missed', models.IntegerField(default=0)),
                ('stage_2_dispatched', models.IntegerField(default=0)),
                ('stage_2_answered', models.IntegerField(default=0)),
                ('stage_2_missed', models.IntegerField(default=0)),
                ('stage_3_dispatched', models.IntegerField(default=0)),
                ('stage_3_answered', models.IntegerField(default=0)),
                ('stage_3_missed', models.IntegerField(default=0)),
                ('answered_count', models.IntegerField(default=0)),
                ('missed_count', models.IntegerField(default=0)),
                ('delay_seconds', models.IntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sarvam_campaigns', to=settings.AUTH_USER_MODEL)),
                ('sarvam_agent', models.ForeignKey(blank=True, help_text='Sarvam voice agent used for this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='conversations.sarvamagent')),
            ],
            options={
                'verbose_name': 'Sarvam Campaign',
                'verbose_name_plural': 'Sarvam Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sarvamcallrecord',
            name='campaign_stage',
            field=models.IntegerField(default=1, help_text='1=Main, 2=Retry 1, 3=Retry 2'),
        ),
        migrations.CreateModel(
            name='SarvamCampaignLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(default='Candidate', max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('applied_position', models.CharField(default='Admission Counselor', max_length=255)),
                ('stage_1_status', models.CharField(choices=[('PENDING', 'Pending'), ('ANSWERED', 'Answered / Picked Up'), ('MISSED', 'Missed / No Answer'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped (Already Picked Up)')], default='PENDING', max_length=50)),
                ('stage_2_status', models.CharField(choices=[('PENDING', 'Pending'), ('ANSWERED', 'Answered / Picked Up'), ('MISSED', 'Missed / No Answer'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped (Already Picked Up)')], default='SKIPPED', max_length=50)),
                ('stage_3_status', models.CharField(choices=[('PENDING', 'Pending'), ('ANSWERED', 'Answered / Picked Up'), ('MISSED', 'Missed / No Answer'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped (Already Picked Up)')], default='SKIPPED', max_length=50)),
                ('final_status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('ANSWERED', 'Answered / Picked Up'), ('MISSED_ALL_RETRIES', 'Missed All 3 Attempts'), ('FAILED', 'Failed')], default='IN_PROGRESS', max_length=50)),
                ('total_attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='conversations.sarvamcampaign')),
                ('last_call_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_lead', to='conversations.sarvamcallrecord')),
                ('stage_1_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_1_lead', to='conversations.sarvamcallrecord')),
                ('stage_2_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_2_lead', to='conversations.sarvamcallrecord')),
                ('stage_3_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_3_lead', to='conversations.sarvamcallrecord')),
            ],
            options={
                'verbose_name': 'Sarvam Campaign Lead',
                'verbose_name_plural': 'Sarvam Campaign Leads',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='sarvamcallrecord',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Campaign this call belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='conversations.sarvamcampaign'),
        ),
    ]
