# Generated by Django 4.2.28 on 2026-09-15 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0015_sarvamcampaign_sarvamcallrecord_campaign_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarvamagent',
            name='allocated_minutes',
            field=models.FloatField(default=5000.0, help_text='Total call minutes limit allocated by Superadmin (e.g. 5000.0 mins)'),
        ),
        migrations.AddField(
            model_name='sarvamagent',
            name='extra_used_seconds',
            field=models.FloatField(default=0.0, help_text='Additional manual seconds used adjustment by Superadmin'),
        ),
        migrations.AddField(
            model_name='sarvamcallrecord',
            name='billed_seconds',
            field=models.IntegerField(default=0, help_text='Billed seconds calculated with 30s pulse (e.g. 20s->30s, 40s->60s)'),
        ),
        migrations.AlterField(
            model_name='sarvamcampaign',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING_MAIN', 'Running Main Campaign'), ('WAITING_RETRY_1', 'Waiting for Retry #1 (5-Min Gap)'), ('RUNNING_RETRY_1', 'Running Retry #1'), ('WAITING_RETRY_2', 'Waiting for Final Retry (5-Min Gap)'), ('RUNNING_RETRY_2', 'Running Retry #2 (Final)'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=50),
        ),
        migrations.CreateModel(
            name='SarvamAgentMinuteAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADD', 'Add Minutes'), ('SUBTRACT', 'Subtract Minutes'), ('SET', 'Set Total Limit')], max_length=20)),
                ('minutes_amount', models.FloatField(help_text='Amount of minutes added/subtracted or new total')),
                ('previous_allocated_minutes', models.FloatField(default=0.0)),
                ('new_allocated_minutes', models.FloatField(default=0.0)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minute_adjustments', to='conversations.sarvamagent')),
            ],
            options={
                'verbose_name': 'Sarvam Agent Minute Adjustment',
                'verbose_name_plural': 'Sarvam Agent Minute Adjustments',
                'ordering': ['-created_at'],
            },
        ),
    ]
