# Generated by Django 4.2.28 on 2026-09-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0016_sarvamagent_allocated_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarvamcampaign',
            name='delay_seconds',
            field=models.IntegerField(default=10),
        ),
    ]
