# Generated by Django 4.2.28 on 2026-09-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0017_alter_sarvamcampaign_delay_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarvamcampaignlead',
            name='extra_variables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sarvamcampaignlead',
            name='language',
            field=models.CharField(default='hi-IN', max_length=50),
        ),
    ]
