# Generated by Django 4.2.28 on 2026-09-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0018_sarvamcampaignlead_extra_variables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarvamcampaignlead',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic Excel/CSV variables like car_model, model, city, area, budget'),
        ),
    ]
