# Generated by Django 4.2.28 on 2026-10-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0019_sarvamcampaignlead_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMaintenanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('message', models.CharField(default='System is under maintenance for 10 minutes. Please try again after 10 minutes.', max_length=255)),
                ('secret_key', models.CharField(default='vtech_maintenance_secret_key_2026', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Maintenance Config',
                'verbose_name_plural': 'System Maintenance Configs',
            },
        ),
        migrations.AlterField(
            model_name='sarvamcallrecord',
            name='billed_seconds',
            field=models.IntegerField(default=0, help_text='Billed seconds calculated with 60s (1 min) pulse (e.g. 1s->60s, 61s->120s)'),
        ),
    ]
