# Generated by Django 4.2.28 on 2026-10-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0020_systemmaintenanceconfig_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemmaintenanceconfig',
            options={},
        ),
        migrations.RemoveField(
            model_name='systemmaintenanceconfig',
            name='secret_key',
        ),
    ]
