# Generated by Django 4.2.28 on 2026-06-05 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_voiceagent_summary'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text="Limits access to this voice agent's data only", null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.voiceagent'),
        ),
    ]
