# Generated by Django 4.2.28 on 2026-06-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_logo_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
