# Generated by Django 4.2.28 on 2026-09-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0015_sarvamcampaign_sarvamcallrecord_campaign_stage_and_more'),
        ('accounts', '0006_userprofile_company_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_sarvam_agents',
            field=models.ManyToManyField(blank=True, help_text='Sarvam voice agents assigned to this user', related_name='assigned_users', to='conversations.sarvamagent'),
        ),
    ]
