# Generated by Django 6.0.3 on 2026-03-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='conversation_state',
            field=models.CharField(default='initial', max_length=50),
        ),
    ]
