# Generated by Django 6.0.3 on 2026-03-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
