# Generated by Django 6.0.1 on 2026-03-19 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_uploadbatch_customer_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='bot.uploadbatch'),
        ),
    ]
