# Generated by Django 6.0.3 on 2026-03-24 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_customer_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('renewal', 'Renewal'), ('new', 'New Insurance')], default='renewal', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='quoted_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='selected_addons',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='selected_coverage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car / SUV / MUV'), ('Bike', 'Bike / Scooter / Moped'), ('Commercial', 'Commercial Vehicle'), ('Auto', 'Auto Rickshaw / E-Rickshaw'), ('Tractor', 'Tractor / Farm Equipment')], default='Car', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatmessage_set', to='bot.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='policy_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
