# Generated by Django 6.0.3 on 2026-03-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_customer_customer_type_customer_quoted_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='conversation_state',
            field=models.CharField(default='inactive', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('renewal', 'Renewal'), ('new', 'New Insurance')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='User', max_length=100),
        ),
    ]
