# Generated by Django 4.2.28 on 2026-05-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_fix_existing_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0)),
                ('missed_calls', models.TextField(default='[]')),
                ('is_active', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Campaign Statuses',
            },
        ),
    ]
