# Generated by Django 4.2.28 on 2026-05-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_campaignstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('phone_list', models.TextField(default='[]')),
                ('total_count', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0)),
                ('answered_count', models.IntegerField(default=0)),
                ('missed_calls', models.TextField(default='[]')),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-started_at'],
            },
        ),
    ]
