# Generated by Django 4.2.28 on 2026-06-08 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_voiceagent_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0013_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='agents.voiceagent'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
