# Generated by Django 4.2.28 on 2026-07-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_campaign_agent_campaign_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='parent_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_campaigns', to='bot.campaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
