# Generated by Django 4.2.28 on 2026-07-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_campaign_parent_campaign_campaign_retry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='remaining_queue',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='suspended_due_to_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaignstatus',
            name='remaining_queue',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='campaignstatus',
            name='suspended_due_to_hours',
            field=models.BooleanField(default=False),
        ),
    ]
