# Generated by Django 4.2.28 on 2026-07-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_campaign_remaining_queue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='answered_calls',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='campaignstatus',
            name='answered_calls',
            field=models.TextField(default='[]'),
        ),
    ]
