# Generated by Django 4.2.28 on 2026-07-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_campaign_answered_calls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstatus',
            name='active_calls',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='campaignstatus',
            name='current_campaign_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignstatus',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
