# Generated by Django 5.2.12 on 2026-04-01 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='User', max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('source', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='outbound', max_length=10)),
                ('customer_type', models.CharField(choices=[('renewal', 'Renewal'), ('new', 'New Insurance')], default='new', max_length=10)),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car / SUV / MUV'), ('Bike', 'Bike / Scooter / Moped'), ('Commercial', 'Commercial Vehicle'), ('Auto', 'Auto Rickshaw / E-Rickshaw'), ('Tractor', 'Tractor / Farm Equipment')], default='Car', max_length=20)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('policy_type', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('conversation_state', models.CharField(default='inactive', max_length=50)),
                ('selected_coverage', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_addons', models.CharField(blank=True, max_length=200, null=True)),
                ('quoted_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_type', models.CharField(blank=True, max_length=20, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sender', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatmessage_set', to='customers.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customers.uploadbatch'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('phone', 'source')},
        ),
    ]
