# Generated by Django 4.2.28 on 2026-09-02 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0011_alter_leadanalysis_lead_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcemakeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('registered_mobile', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('city_state', models.CharField(blank=True, max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=20)),
                ('machine_model_no', models.CharField(blank=True, max_length=100)),
                ('machine_sr_no', models.CharField(blank=True, max_length=100)),
                ('issue_type', models.CharField(choices=[('Blast Freezer', 'Blast Freezer'), ('Chiller', 'Chiller'), ('Freezer', 'Freezer'), ('Other', 'Other')], default='Other', max_length=50)),
                ('issue_description', models.TextField(blank=True)),
                ('google_sheet_synced', models.BooleanField(default=False, help_text='True if ticket has been sent to Google Sheet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='icemake_ticket', to='conversations.conversation')),
            ],
        ),
    ]
